version: '3.8'

services: 
    redis:
        image: dekau/storypoint-redis:latest
        ports:
        - 6379
    server:
        image: dekau/storypoint-server:latest
        ports: 
        - 8080:8080
        environment:
            REDIS_HOST: redis
    web:
        image: dekau/storypoint-web:latest
        ports:
        - 80:80