name: Publish
on:
  push:
    tags:
    - '*'
jobs:
  build:
    strategy:
      matrix:
        kind: ['web', 'server', 'redis']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get tag version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Run build script
        run: ./build-${{ matrix.kind }}.sh
      - name: Get image hash
        id: get_image_hash
        run: echo ::set-output name=IMAGE_HASH::$(docker images | awk -e '$1 ~ /storypoint-${{ matrix.kind }}/ {print $3}')
      - name: Tag release
        run: docker tag ${{ steps.get_image_hash.outputs.IMAGE_HASH }} dekau/storypoint-${{ matrix.kind }}:${{ steps.get_version.outputs.VERSION }}
      - name: Tag latest
        run: docker tag ${{ steps.get_image_hash.outputs.IMAGE_HASH }} dekau/storypoint-${{ matrix.kind }}:latest
      - name: Push release
        run: docker push dekau/storypoint-${{ matrix.kind }}:${{ steps.get_version.outputs.VERSION }}
      - name: Push latest
        run: docker push dekau/storypoint-${{ matrix.kind }}:latest

      # - name: Publish Docker Hub
      #   uses: elgohr/Publish-Docker-Github-Action@2.14
      #   with:
      #     name: "dekau/storypoint-${{ matrix.kind }}"
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     dockerfile: Dockerfile
      #     workdir: ${{ matrix.kind }}
      #     cache: true
      #     tags: "latest,${{ steps.get_version.outputs.VERSION }}"
